### Auth

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "name",
  "email": "namename1@gmail.com",
  "password": "123456abc"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "namename1@gmail.com",
  "password": "123456abc"
}


###

POST http://localhost:3000/post
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjE1OWRlNTgzNDNkNWRiNGFlOGUwZGQiLCJlbWFpbCI6Im5hbWVuYW1lMUBnbWFpbC5jb20iLCJpYXQiOjE3MTI3Nzc0NjMsImV4cCI6MTcxMjc4MTA2M30.Nmgby37WwO5WLSCS2FBJu0bfjxBZjaPm3TcA520nukM
Content-Type: application/json

{
  "text": "hello!!!"
}

###

POST http://localhost:3000/auth/refreshToken
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjE1OWRlNTgzNDNkNWRiNGFlOGUwZGQiLCJlbWFpbCI6Im5hbWVuYW1lMUBnbWFpbC5jb20iLCJpYXQiOjE3MTI4MzE0NDR9.gZaoSCdpBbJFbV-DEKjs7uHiQDeJ2qbMtQT60j-VZYo
