### Auth

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "name",
  "email": "namename1@gmail.com",
  "password": "123456abc"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "namename1@gmail.com",
  "password": "123456abc"
}


###

POST http://localhost:3000/post
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjE1OWRlNTgzNDNkNWRiNGFlOGUwZGQiLCJlbWFpbCI6Im5hbWVuYW1lMUBnbWFpbC5jb20iLCJpYXQiOjE3MTI2OTI3MTMsImV4cCI6MTcxMjY5NjMxM30.vKiT4vegcGs59-sieOghvmZBYX2xWLHbTm2eu5zGXwg

###

POST http://localhost:3000/auth/refreshToken
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjE1OWRlNTgzNDNkNWRiNGFlOGUwZGQiLCJlbWFpbCI6Im5hbWVuYW1lMUBnbWFpbC5jb20iLCJpYXQiOjE3MTI2OTI3MTN9.5HSrEyhmJ-O9LNaiDAjdYNY17Mm8t1eL-KhIIlOLqZg
