### Auth

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "name",
  "email": "namename1@gmail.com",
  "password": "123456abc"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "namename1@gmail.com",
  "password": "123456abc"
}


###

POST http://localhost:3000/post
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjExN2JmYjE3NjE5M2QyNTY5ZmQ4NTIiLCJlbWFpbCI6Im5hbWVuYW1lMUBnbWFpbC5jb20iLCJpYXQiOjE3MTI2NzE0ODUsImV4cCI6MTcxMjY3NTA4NX0.lCpverpkFoMrkcB9Ef76GOTED9kvFL8zV7qxu8aK20E
